nav:
  Home: /
  Sobre Mim: /sobre-mim/
  Artigos: /artigos/
  Projetos: http://github.com/aferreira44

projects_url: http://github.com/aferreira44

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/aferreira44
        twitter: https://twitter.com/aferreira44
        facebook: https://facebook.com/aferreira44
        linkedin: https://www.linkedin.com/in/aferreira44/
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: andreferreirame
    google_analytics: UA-49658133-1

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
